- name: 📂 Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # Update this path to match your specific domain folder
          server-dir: ./nexus.66ghz.com/htdocs/
          protocol: ftp
          port: 21
          security: loose
